### ISSUE TITLE
Production doesn't work

### ISSUE THREAD

**Issue by joshuajott** [justeat/ApplePayJSSample#21]
Hello,  great example.  I use our p12 cert and things work great. Apple Pay api responds and everything.
But as soon as I publish to a production environment I am getting "The client certificate credentials were not recognized".  

How can it work just fine in localhost debug mode but as soon as its sits out on an IIS site it doesnt?
The site as per instructions is on the proper domain name specified in the merchant config in apple dev portal.     

Is there any work around? Could I just leave it in debug mode and run it outside of IIS  on a special port?
Would love to understand whats happening.

**Comment by martincostello** [comment]
Hi Joshua,

Could you clarify exactly where you get the "_The client certificate credentials were not recognized_" error from? Is it an exception message in the C# code, or is it an error client-side from the Apple Pay JS SDK? If it's from the C# code, can you include a stack trace?

All I can think of from your description is that you've misconfigured the client certificate to use with the `HttpClient` for merchant validation in your production website.

I've got a version of this sample code running in an Azure App Service website under IIS as "Production", and it works as expected.

**Comment by martincostello** [comment]
I'll close this issue if we don't get an update to our follow-up questions within another 7 days.
