### ISSUE TITLE
Merchant Identifier

### ISSUE THREAD

**Issue by Serrel** [justeat/ApplePayJSSample#28]
Hi!

I have a question on the usage of MerchantIdentifier.
If I understand the code correctly, MerchantIdentifier is loaded from certificate
```
var extension = certificate.Extensions["1.2.840.113635.100.6.32"];
return Encoding.ASCII.GetString(extension.RawData).Substring(2);
```
As stated in [documentation](https://developer.apple.com/library/content/documentation/PassKit/Reference/PaymentTokenJSON/PaymentTokenJSON.html),  OID 1.2.840.113635.100.6.32 contains the hex encoded hash of the merchant ID.

But then on session validation that hash is sent as a merchantIdentifier, although [apple example](https://developer.apple.com/documentation/apple_pay_on_the_web/apple_pay_js_api/requesting_an_apple_pay_payment_session) shows that actual human readable identifier should be sent.

Is it a mistake, or it actually doesn't matter what values you send to apple on validation?

**Comment by martincostello** [comment]
Yes, in my experience, you can send both. Reading it from the certificate itself and sending the hash is less configuration to worry about though, which is why I decided to code the sample that way.

**Comment by Serrel** [comment]
Understood, thank you!
