### ISSUE TITLE
Can't get to onpaymentauthorized

### ISSUE THREAD

**Issue by OpenPath** [justeat/ApplePayJSSample#42]
### Expected behaviour

Use the Pay with Touch ID and receive the data from the onpaymentauthorized event

### Actual behaviour

I'm using {staticsubdomain}.ngrok.io to test on my local environment, I've registered the domain in the Developers website and I believe Everything is setup properly.

The Apple Pay button shows up on my iPhone
The payment bar pops up and the onvalidatemerchant, onpaymentmethodselected and other methods are getting hit and I get to the point where I can use my finger print on the Pay with Touch ID using a sandbox account and a test credit card.

However, when I use my finger print the circle spins for a second and then says Payment not Completed and it doesn't hit onpaymentauthorized.

It works perfect with the PolyFill on my Windows machine, but not without on my iPhone. I bought a used mac so I could inspect and debug in Safari; hoping to find some sort of message from the ApplePayJS in the browser, but nothing.

Searched the internet added a ton of logging in the JS can't seem to find anything to point me in the right direction. I've been working on this for a few months.  Hoping you might be able to point me in the right direction.

Cheers!

**Comment by martincostello** [comment]
Hi Jason - off  the top of my head, here's the first few things I'd check if you haven't already:
  * Apple has verified you control the domain after you added it by you placing the domain verification file on your server at the right URL.
  * TLS 1.2 is enabled ([example](https://github.com/justeat/ApplePayJSSample/blob/f654125f1a51cdb55b239f2b30092f2443abb9c1/src/ApplePayJS/Startup.cs#L67-L70)).
  * Your application is correctly loading the client certificate from disk/store and attaching it to requests using HttpClient to get the metadata.
  * Your website's certificate is publicly trusted (e.g. not self-signed).
  * The hostname you're using on the device matches _exactly_ any registered in the Apple setup and that you're loading it over HTTPS.

The merchant certificate I use to test this sample integration has expired so I can't check right now that it's all still working correctly, but is something I can pick up next week if necessary to validate no problems on our end with the sample either.

**Comment by OpenPath** [comment]
Martin,

Thank you so much for your response. I reviewed everything and it all looked good, but still wasn't working.

- [x] Apple has verified you control the domain after you added it by you placing the domain verification file on your server at the right URL.
- [x]  TLS 1.2 is enabled.
- [x] Your application is correctly loading the client certificate from disk/store and attaching it to requests using HttpClient to get the metadata.
- [x] Your website's certificate is publicly trusted (e.g. not self-signed).
- [x] The hostname you're using on the device matches exactly any registered in the Apple setup and that you're loading it over HTTPS.

However, I uploaded it to one of our servers and tested it out and it worked perfect.  As far as I can tell you can not use/test this behind an [ngrok](https://ngrok.com/) proxy (although maybe I just don't have it configured correctly).

If someone does know how to successfully test this behind ngrok, it would make development much easier and would love to hear how you did it!  Here are the two ngrok commands I used to test the site behind:

- ngrok http https://localhost:44399 -host-header="localhost:52623" -subdomain=openpath-apple-pay
- ngrok http 52623 -host-header="localhost:52623" -subdomain=openpath-apple-pay -bind-tls=true

@martincostello This is an awesome example C# framework to get started off of, thank you!

**Comment by martincostello** [comment]
Thanks for posting the eventual solution back. Glad you got it working in the end!

**Comment by lonelyjie** [comment]
I had the same problem but couldn't solve it
