### ISSUE TITLE
Passbook

### ISSUE THREAD

**Issue by sairaut** [justeat/ApplePayJSSample#7]
Hi Martin,

This is not related to your project but thought of checking with you. I am trying to host the below project on Azure:

https://github.com/rickschrader/PassbookWebApiService

I have installed the Pass Certificate the same way we did . But not sure how to install the Apple WWDR (WorldWide Developer Relations) certificate which is .CER format and it is not getting converted into PFX.

Can you please be able to load it and see if you are able to generate the pass successfully?

Your help on this would be much appreciated!

Thanks.

(Apologies for adding this into the Issues section. I shall delete it later)

**Comment by martincostello** [comment]
@sairaut As far as I'm aware, WWDR is an Apple-issued intermediate certificate to which only the public key is issued, hence it being in ```.cer``` format, so cannot be converted into ```.pfx``` as you don't have the private key. I think for Azure you best bet is to re-export your PassBook certificate as a ```.pfx``` with the entire certificate chain all the way up to the root. That way the Azure deployment should have access to all the certificates to establish trust.

**Comment by sairaut** [comment]
Thanks Martin. I tried that. But it is not downloading the pkpass file. will you be able to host this project and Azure and check. Sorry to bother you :)

**Comment by martincostello** [comment]
Sorry, I've not used PassBook myself and don't have access to an Apple Developer account anymore to try this out.
