### ISSUE TITLE
onvalidatemerchant return error

### ISSUE THREAD

**Issue by TarekMohamed92** [justeat/ApplePayJSSample#91]
when i try Validate Function inside onvalidatemerchant 
return 
Unable to read data from the transport connection: An existing connection was forcibly closed by the remote
could you help me detect where error please ?

**Comment by martincostello** [comment]
That sounds like your back-end for handling the merchant validation is broken.

**Comment by TarekMohamed92** [comment]
but i just change some values on current repo code 
which place i should  search to fix certificate or where ?

**Comment by martincostello** [comment]
Without seeing what you've changed and/or any error log(s), I can't really help you with this problem as I'd just be guessing at what might be wrong and why.
