### ISSUE TITLE
The SSL connection could not be established - onvalidatemerchant

### ISSUE THREAD

**Issue by gursharan666** [justeat/ApplePayJSSample#95]
Hi Martin,

I'm trying to add apple pay on my website, my site built in asp.net 4.5, and your code in .net core, so I have build a test project in .net core.

I have generated PFX file on MackbookPro, I have followed below steps
https://blog.aclerbois.be/blog/2020/01/09/Generates-a-pfx-for-Apple-Pay

on this js method onvalidatemerchant, I'm getting below error message from server

The SSL connection could not be established, see inner exception.exception :

System.ComponentModel.Win32Exception (0x8009030D): The credentials supplied to the package were not recognized   at System.Net.SSPIWrapper.AcquireCredentialsHandle(ISSPIInterface secModule, String package, CredentialUse intent, SCHANNEL_CRED* scc)   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCHANNEL_CRED* secureCredential)   at System.Net.Security.SslStreamPal.AcquireCredentialsHandleSchannelCred(X509Certificate certificate, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(SslStreamCertificateContext certificateContext, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)   at System.Net.Security.SecureChannel.AcquireClientCredentials(Byte[]& thumbPrint)   at System.Net.Security.SecureChannel.GenerateToken(ReadOnlySpan`1 inputBuffer, Byte[]& output)   at System.Net.Security.SecureChannel.NextMessage(ReadOnlySpan`1 incomingBuffer)   at System.Net.Security.SslStream.ProcessBlob(Int32 frameSize)   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)

I'm using Apple Pay Merchant Identity Certificate

Thanks

**Comment by martincostello** [comment]
Does ASP.NET 4.5 support reading a file in the format you've generated it? Does the version of Windows you're using support handling a certificate in the format you've generated it? Have you configured the appropriate password to open the certificate?

I can't really support you running an adapted version of this code on an unsupported version of .NET that the code wasn't designed or tested to run on.

**Comment by gursharan666** [comment]
I'm testing this in .net core, using your sample code for testing.

Window server 2016

Yes, I have configured the password to open the certificate, loading certificate from disk

forgot about ASP.NET 4.5, I'm just using .net core

getting error on this method

[HttpPost]
        [Produces(MediaTypeNames.Application.Json)]
        [Route("applepay/validate", Name = "MerchantValidation")]
        public async Task<IActionResult> Validate([FromBody] ValidateMerchantSessionModel model, CancellationToken cancellationToken = default)
        {
            // You may wish to additionally validate that the URI specified for merchant validation in the
            // request body is a documented Apple Pay JS hostname. The IP addresses and DNS hostnames of
            // these servers are available here: https://developer.apple.com/documentation/applepayjs/setting_up_server_requirements
            if (!ModelState.IsValid ||
                string.IsNullOrWhiteSpace(model?.ValidationUrl) ||
                !Uri.TryCreate(model.ValidationUrl, UriKind.Absolute, out Uri? requestUri))
            {

                return BadRequest();
            }

            try
            {
                // Create the JSON payload to POST to the Apple Pay merchant validation URL.
                var request = new MerchantSessionRequest()
                {
                    DisplayName = _options.StoreName,
                    Initiative = "web",
                    InitiativeContext = Request.GetTypedHeaders().Host.Value,
                    MerchantIdentifier = _certificate.GetMerchantIdentifier(),
                };

                JsonDocument merchantSession = await _client.GetMerchantSessionAsync(requestUri, request, cancellationToken);

               // _logger.LogInformation(merchantSession.RootElement.ToString());
                // Return the merchant session as-is to the JavaScript as JSON.
                return Json(merchantSession.RootElement);
            }
            catch (Exception ex)
            {
                _logger.LogInformation(ex.Message);
                return Json(ex.Message + " --- exception -- :"+ex.InnerException +"------"+ requestUri);
            }
        }
